title: Film Storyboards
author: Film Storyboards
url: https://film-storyboards.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl:
google_analytics_key:

# SEO tags values (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/author.jpg
tagline: Story artist portfolio site
description: Film Storyboards is a one-person studio focusing on production design and visual storytelling. I draw for films, animation, and cross media projects. Call for a tailored solution to visualize, pitch, plan, and budget your film or project.
twitter:
  username: FilmStoryboards  # twitter username without the @ symbol
  card: summary
facebook:
  publisher: filmstoryboards
phone: "+32 (0) 475 418 327"
social:
  name: Film Storyboards
  links:
    - https://twitter.com/FilmStoryboards
    - https://filmstoryboards.medium.com
    - https://www.pinterest.com/filmstoryboards
    - https://www.instagram.com/filmstoryboards
    - https://www.facebook.com/filmstoryboards
    - https://www.linkedin.com/company/film-storyboards
image: /images/film-storyboards-screenshot.png
locale: En

# No analytics it's a waste of time

# Date format
# refer to https://shopify.github.io/liquid/filters/date/ to customize this
date_format: "%b %-d, %Y"

# Reading Files
include:
  - .htaccess
  - _pages

# Outputting
permalink: /:title/
paginate_path: "/page:num/"
timezone: Europe/Paris

pagination:
  enabled: True
  collection: posts
  per_page: 5

# Plugins
plugins:
#  - jekyll-picture-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  # Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled: 'all'
  layout: 'archive-taxonomy'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  category_archive:
    type: liquid
